Repository AY2021S1-CS2113T-W11-3/tp, pull requests merged in 2020-11, with the labels that each got.

#171 Update upper sections of UG
  docs/UserGuide.md
  src/main/java/ui/Printer.java
Labels: type.Task

#175 Finish UG commands
  docs/UserGuide.md
  src/main/java/ui/Printer.java
Labels: type.Task

#177 Added elements to UG
  docs/UserGuide.md
Labels: priority.Medium

#201 First Iteration of user guide elements - Theodore
  docs/UserGuide.md
Labels: priority.Medium

#217 Revise UG
  docs/UserGuide.md
Labels: type.Task

#198 Fix redundant prompts for command flags also Add Abner PPP draft
  docs/UserGuide.md
  docs/team/abner.md
  docs/team/abnermtj.md
  src/main/java/cheatlogs/CheatLogs.java
  src/main/java/parser/Parser.java
  src/main/java/ui/UserSession.java
Labels: type.Task

#236 Update DG first sections structure
  docs/DeveloperGuide.md
Labels: type.Task

#246 Error message when favouriting a favourited cheatsheet and Add command required flags
  docs/UserGuide.md
  src/main/java/command/AddCommand.java
  src/main/java/command/Command.java
  src/main/java/command/EditCommand.java
  src/main/java/command/FavouriteCommand.java
  src/main/java/parser/Parser.java
  src/main/java/ui/Printer.java
  src/main/java/ui/UserSession.java
  src/test/java/command/AddCommandTest.java
  src/test/java/parser/ParserTest.java
Labels: type.Task

#252 Add java docs to deletion commands + bug fixes
  src/main/java/cheatlogs/CheatLogs.java
  src/main/java/cheatsheet/CheatSheet.java
  src/main/java/command/AddCommand.java
  src/main/java/command/ClearCommand.java
  src/main/java/command/Command.java
  src/main/java/command/DeleteCommand.java
  src/main/java/command/EditCommand.java
  src/main/java/command/FavouriteCommand.java
  src/main/java/command/FindCommand.java
  src/main/java/command/FinderCommand.java
  src/main/java/command/SettingsCommand.java
  src/main/java/command/ViewCommand.java
  src/main/java/parser/Parser.java
  src/main/java/ui/ConsoleColorsEnum.java
  src/main/java/ui/Printer.java
  src/main/java/ui/Ui.java
  src/main/java/ui/UserSession.java
Labels: type.Task

#258 Refining storage capabilities
  src/main/java/command/ClearCommand.java
  src/main/java/exception/InvalidParamException.java
  src/main/java/storage/DataFileDestroyer.java
  src/main/java/storage/DataFileReader.java
Labels: severity.Medium

#264 Abner user sesh
  src/main/java/command/AddCommand.java
  src/main/java/parser/Parser.java
Labels: type.Bug

#282 Abner PPP
  docs/team/abnermtj.md
Labels: type.Task

#273 Abner clear delete Junit
  src/main/java/command/ClearCommand.java
  src/main/java/command/DeleteCommand.java
  src/main/java/parser/Parser.java
  src/test/java/command/ClearCommandTest.java
  src/test/java/command/DeleteCommandTest.java
  src/test/java/command/EditCommandTest.java
  src/test/java/command/ExitCommandTest.java
  src/test/java/command/HelpTest.java
  src/test/java/command/stuba/CheatSheetListStub.java
  src/test/java/command/stuba/DataFileDestroyerStub.java
  src/test/java/command/stuba/DataFileReaderStub.java
  src/test/java/command/stuba/EditorStub.java
  src/test/java/command/stuba/UiStub.java
Labels: type.Task
